title: zbaxrl's blog
author: zbaxrl2000
language: zh-CN
timezone: Asia/Shanghai

url: http://ai.mky.moe
root: /
permalink: :year/:title/

source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

new_post_name: :title.md
default_layout: post
titlecase: false
external_link: true
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  hljs: true
  tab_replace:
  
index_generator:
  path: ''
  per_page: 5
  order_by: -date
  
default_category: uncategorized
category_map:
tag_map:

date_format: YYYY-MM-DD
time_format: HH:mm:ss

per_page: 5
pagination_dir: page

theme: custom

pandoc:
  toc: true
  mathEngine: katex

deploy:
  type:
